[2025-08-22T04:06:32.816+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T04:06:32.904+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_merchant_data manual__2025-08-22T04:01:37+00:00 [queued]>
[2025-08-22T04:06:32.949+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_stg.load_merchant_data manual__2025-08-22T04:01:37+00:00 [queued]>
[2025-08-22T04:06:32.949+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2025-08-22T04:06:33.026+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load_merchant_data> on 2025-08-22 04:01:37+00:00
[2025-08-22T04:06:33.067+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=841) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-22T04:06:33.078+0000] {standard_task_runner.py:72} INFO - Started process 849 to run task
[2025-08-22T04:06:33.090+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_stg', 'load_merchant_data', 'manual__2025-08-22T04:01:37+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_stg.py', '--cfg-path', '/tmp/tmpjn3uc750']
[2025-08-22T04:06:33.107+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask load_merchant_data
[2025-08-22T04:06:33.297+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_stg.load_merchant_data manual__2025-08-22T04:01:37+00:00 [running]> on host 21c40e4c1785
[2025-08-22T04:06:34.308+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_stg' AIRFLOW_CTX_TASK_ID='load_merchant_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T04:01:37+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T04:01:37+00:00'
[2025-08-22T04:06:34.311+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T04:06:34.602+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T04:06:36.504+0000] {logging_mixin.py:190} INFO - Data loaded to stg.stg_container_ships successfully.
[2025-08-22T04:06:36.527+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T04:06:36.584+0000] {logging_mixin.py:190} INFO - Data loaded to stg.stg_merchant_ship_product_master successfully.
[2025-08-22T04:06:36.585+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-08-22T04:06:36.607+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T04:06:36.610+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline_stg, task_id=load_merchant_data, run_id=manual__2025-08-22T04:01:37+00:00, execution_date=20250822T040137, start_date=20250822T040632, end_date=20250822T040636
[2025-08-22T04:06:36.698+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-08-22T04:06:36.743+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T04:06:36.746+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
