[2025-08-22T05:53:59.935+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-22T05:53:59.973+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_mart.transform_special_ships manual__2025-08-22T05:53:55+00:00 [queued]>
[2025-08-22T05:53:59.985+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_mart.transform_special_ships manual__2025-08-22T05:53:55+00:00 [queued]>
[2025-08-22T05:53:59.985+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-08-22T05:54:00.007+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): transform_special_ships> on 2025-08-22 05:53:55+00:00
[2025-08-22T05:54:00.028+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2338) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-22T05:54:00.034+0000] {standard_task_runner.py:72} INFO - Started process 2346 to run task
[2025-08-22T05:54:00.037+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_mart', 'transform_special_ships', 'manual__2025-08-22T05:53:55+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_mart.py', '--cfg-path', '/tmp/tmpdc5y7rmj']
[2025-08-22T05:54:00.043+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask transform_special_ships
[2025-08-22T05:54:00.160+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_mart.transform_special_ships manual__2025-08-22T05:53:55+00:00 [running]> on host 21c40e4c1785
[2025-08-22T05:54:00.341+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_mart' AIRFLOW_CTX_TASK_ID='transform_special_ships' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T05:53:55+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T05:53:55+00:00'
[2025-08-22T05:54:00.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-22T05:54:00.384+0000] {sql.py:282} INFO - Executing: 
        DROP TABLE IF EXISTS mart.special_ships_clean;

        CREATE TABLE mart.special_ships_clean AS
        SELECT
            project_id,
            contract_date,
            business_unit,
            product_type,
            country,
            CAST(revenue AS BIGINT) AS revenue,
            CAST(build_duration_days AS INTEGER) AS build_duration_days,
            delivery_date,
            stage_progress,
            geopolitical_risk_index,
            mro_contract_revenue,
            patrol_days_per_maintenance_cycle,
            model_type,
            fleet_size
        FROM stg.special_ships_stg
        WHERE contract_date BETWEEN '2025-08-21 00:00:00' AND '2025-08-22 00:00:00';
        
[2025-08-22T05:54:00.409+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T05:54:00.433+0000] {base.py:84} INFO - Retrieving connection 'datalake_1'
[2025-08-22T05:54:00.467+0000] {sql.py:509} INFO - Running statement: 
        DROP TABLE IF EXISTS mart.special_ships_clean;

        CREATE TABLE mart.special_ships_clean AS
        SELECT
            project_id,
            contract_date,
            business_unit,
            product_type,
            country,
            CAST(revenue AS BIGINT) AS revenue,
            CAST(build_duration_days AS INTEGER) AS build_duration_days,
            delivery_date,
            stage_progress,
            geopolitical_risk_index,
            mro_contract_revenue,
            patrol_days_per_maintenance_cycle,
            model_type,
            fleet_size
        FROM stg.special_ships_stg
        WHERE contract_date BETWEEN '2025-08-21 00:00:00' AND '2025-08-22 00:00:00';
        , parameters: None
[2025-08-22T05:54:00.469+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "stg.special_ships_stg" does not exist
LINE 20:         FROM stg.special_ships_stg
                      ^

[2025-08-22T05:54:00.485+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline_mart, task_id=transform_special_ships, run_id=manual__2025-08-22T05:53:55+00:00, execution_date=20250822T055355, start_date=20250822T055359, end_date=20250822T055400
[2025-08-22T05:54:00.510+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-22T05:54:00.514+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 44 for task transform_special_ships (relation "stg.special_ships_stg" does not exist
LINE 20:         FROM stg.special_ships_stg
                      ^
; 2346)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "stg.special_ships_stg" does not exist
LINE 20:         FROM stg.special_ships_stg
                      ^

[2025-08-22T05:54:00.545+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-08-22T05:54:00.555+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-08-22T05:54:00.574+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-22T05:54:00.580+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
